[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/login"
  to = "/public/login.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/public/admin.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/status"
  to = "/.netlify/functions/api"
  status = 200